### ISSUE TITLE
ModuleNotFoundError: No module named 'brightpi'

### ISSUE THREAD

**Issue by codeclinic** [sjchiass/trilobot_controls#2]
Hi,

If I run fastapi_remote.py I get ModuleNotFoundError: No module named 'brightpi'.

However, I can't find any references as to how to install BrightPi. Could you let me know what I need to install, to get past this?

Thanks.

**Comment by sjchiass** [comment]
@codeclinic  I pushed some changes to https://github.com/sjchiass/trilobot_controls/tree/main/pyqt

([BrightPi](https://learn.pi-supply.com/make/bright-pi-quickstart-faq/) is small board with visible and IR LEDs you can use to give headlights to the Trilobot. You can see it used for nightvision here: https://sjchiass.com/nightvision-robot.html#nightvision-robot)

I've pushed a new version of `fastapi_remote.py` that only imports BrightPi if you activate the headlights. If you leave that control alone, it won't try importing it.

**Comment by sjchiass** [comment]
There is also a web GUI that only has a few dependencies on the RPi: https://github.com/sjchiass/trilobot_controls/tree/main/web_gui
